### ISSUE TITLE
OpenAPI docs

### ISSUE THREAD

**Issue by Mozzo1000** [Mozzo1000/booklogr#7]
All API routes should be documented with the OpenAPI specification.
[flasggr](https://github.com/flasgger/flasgger) is a great tool for this, allowing the routes to be documented in code while also exporting an OpenAPI specification and UI.

The following routes needs to be documented:
## Books
- [x] `GET` /v1/books
- [x] `POST` /v1/books
- [x] `PATCH` /v1/books/<id>
- [x] `DELETE` /v1/books/<id>
- [x] `GET` /v1/books/<id>/notes
- [x] `POST` /v1/books/<id>/notes

## Notes
- [x] `DELETE` /v1/notes/<id>
- [x] `PATCH` /v1/notes/<id>

## Profiles
- [x] `GET` /v1/profiles/<display_name>
- [x] `GET` /v1/profiles
- [x] `POST` /v1/profiles
- [x] `PATCH` /v1/profiles

## Files
- [x] `GET`/v1/files/<filename>
- [x] `GET`/v1/files

## Tasks
- [x] `GET`/v1/tasks/<id>
- [x] `POST` /v1/tasks
- [x] `POST` /v1/tasks/retry

**Comment by arpanghosh8453** [comment]
Hello @Mozzo1000 

This is amazing application, I am interested to know is there an available API documentation I can look for? I want to automate the progress tracking and notes parsing from my exported clippings.

**Comment by Mozzo1000** [comment]
Hi @arpanghosh8453 
Thank you for appreciating this project. 
The api exposes an interactive swagger site on the `/docs` route. 
Example, for the demo instance I am hosting the documentation can be found https://api.demo.booklogr.app/docs
It might not be super clear what each endpoint does, in that case feel free to ask and I will try and clarify.

I should make this clear that there is an api that can be used for such cases as yours and maybe even export the api reference to our documentation site.

**Comment by arpanghosh8453** [comment]
Thank you for your reply! I can make this work by stealing the Authorization token from the browser session, but can you give guidance on how to generate this with the username and password?

**Comment by Mozzo1000** [comment]
> [..] can you give guidance on how to generate this with the username and password?

Of course! I do see that the authentication endpoints are not in the OpenAPI specs, my apologies for that.

I will give you some examples that work with curl. 
You send data as JSON to the endpoints.
### Add new user
```sh
curl -X POST "http://API_URL/v1/register" \
  -H "Content-Type: application/json" \
  -d '{
    "email": "user@example.com",
    "name": "John Doe",
    "password": "securepassword123"
  }'
```
This will give you the response,
```JSON
{"message":"Account with email user@example.com was created","status":"verified"}
```

You can then use that user to login and thus authenticate,
### Login
```sh
curl -X POST "http://API_URL/v1/login" \
  -H "Content-Type: application/json" \
  -d '{
    "email": "user@example.com",
    "password": "securepassword123"
  }'
```

This will return JSON with the access token, refresh token and other information.

```JSON
{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MjU4NDU4OCwianRpIjoiMGI4MmViMWItZTc2Yi00Yzk3LWFjNTgtZjc1MTQzNGJlYzA5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzZXJAZXhhbXBsZS5jb20iLCJuYmYiOjE3NTI1ODQ1ODgsImNzcmYiOiJhMDNiMTIzOS01MTgyLTQ5N2MtOTk4Zi1iNDk3MmFjOTk1OGMiLCJleHAiOjE3NTMwMTY1ODgsInJvbGUiOiJ1c2VyIiwiaWQiOjJ9.1yJAGjy3UQGfQ1Ovx5QCpjkrmmwkxRyGg8EgsPlwGUs",

"email":"user@example.com",
"id":2,
"name":"John Doe",
"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MjU4NDU4OCwianRpIjoiMTdiNWZiZjEtZDI2Yi00NGMzLWFhMDMtZTk3N2Y5Zjg2YzY4IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwibmJmIjoxNzUyNTg0NTg4LCJjc3JmIjoiNGFiMWE1NjQtZDc3Yy00YTEyLTkyYTgtMTE5N2EyMTVkZGYxIiwiZXhwIjoxNzU1MTc2NTg4fQ.4Py1F_W_MXAzMweuobPHwqWLY8FIvl3Li2gh6PMsy4k",
"role":"user",
"status":"active",
"verification":{
    "status":"verified"
}}
```

The access token is then used as a Bearer token to any endpoint that requires authentication.
The access token is set to expire after 5 days. requiring a new login after that.

The `API_URL` seen in the example is the IP or domain name, including any specific port to the api container.

Does this help?
